### ISSUE TITLE
Could we get a version for 1.19.2?

### ISSUE THREAD

**Issue by Neonit** [Stoutscientist/XPFromHarvest#1]
The original mod stops at 1.19 and this starts at 1.19.4, whereas many mods picked 1.19.2 out of the 1.19 branch. I think it would help a lot of players.

**Comment by Stoutscientist** [comment]
Thanks for the suggestion! I don't have too much time to update it right now but I'll try over the coming weeks.

**Comment by Stoutscientist** [comment]
Done in 41484c271805c84ba827bc98e57b7d63b82ae269, that was actually a lot easier than I expected lol
